# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingformapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='day',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
