# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testingformapp', '0002_auto_20181003_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingformapp.Option')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
