# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingformapp', '0003_auto_20181003_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='close_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
